### ISSUE TITLE
Compute Intensive Processes

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/422-Final-Project#3]
> Create a set of processes that do not request I/O or synchronization services. These are just fillers to take up time. Dynamically create and terminate with no more than 25 running at a time.

1. Change PCB so that they are multipurpose. Can probably just not add I/O stuff to the PCB upon creation and/or add a flag.
2. Limit the max number of compute intensive processes to 25.

**Comment by mrcshaw** [comment]
1. Change PCB so that they are multipurpose. (Added member to PCB process_type enum called intensive.)
Can probably just not add I/O stuff to the PCB upon creation and/or add a flag.(PCB now has a new function to create compute intensive processes. e)

2. Limit the max number of compute intensive processes to 25. (A static int to count how many and disallowing more than 25. scheduler.c has some test code. creating a cpu intensive pcb's increments counter .calling pcb_free decrements the counter only for cpu intensive pcb's)

**Comment by tjsg1992** [comment]
Okay, this is for sure done now. Compute Intense processes are created upon start up and context switching (with a 5% chance), and function identically to IO pcbs except that they do not make trap calls.
